# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chatbotllama2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerjcr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_25c52be9253340b4955529425925068a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_74583479fb4440ceb546f4acdaf5f93e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerjcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_25c52be9253340b4955529425925068a }}/testdockerjcr/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chatbotllama2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_794172e7c0b843c6b1709c115678d878 }}
        images: 'testdockerjcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_25c52be9253340b4955529425925068a }}/testdockerjcr/mltest:${{ github.sha }}'