# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chatbotllama

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerjcr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_214ade2ab97d4307bf2eee9f65be899f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_26155b0c4b484e6c920c94cac4fb0bd2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerjcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_214ade2ab97d4307bf2eee9f65be899f }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chatbotllama'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_37b31beb1151418bb6515cf4d9bae09d }}
        images: 'testdockerjcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_214ade2ab97d4307bf2eee9f65be899f }}/mltest:${{ github.sha }}'