# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chatbotllama

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerjcr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e014778d400c4b61953da7e614774fd3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_90aa303138214609a3f471b348416592 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerjcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e014778d400c4b61953da7e614774fd3 }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chatbotllama'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_87fb4470e5b94ac8965bb25cf7fdc662 }}
        images: 'testdockerjcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e014778d400c4b61953da7e614774fd3 }}/mltest:${{ github.sha }}'