# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chatbotllama2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerjcr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dc73bbccb390463189bc27410d9d17d8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_703707fbbac8406da2b1fcb0488980f1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerjcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dc73bbccb390463189bc27410d9d17d8 }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chatbotllama2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_03ff43ac6579415695e160220c2cd841 }}
        images: 'testdockerjcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dc73bbccb390463189bc27410d9d17d8 }}/mltest:${{ github.sha }}'