# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chatbotllama

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerjcr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_689f399141e74cc6a8032f9c2eb2a466 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2dccad57d7fb46cc81bad0f5c69e931b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerjcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_689f399141e74cc6a8032f9c2eb2a466 }}/testdockerjcr/testdockerjcr/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chatbotllama'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5f4199f5684846078faa5e91e5fae6d4 }}
        images: 'testdockerjcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_689f399141e74cc6a8032f9c2eb2a466 }}/testdockerjcr/testdockerjcr/mltest:${{ github.sha }}'